"""User and profile table updated

Revision ID: 2d7b0d4e5f63
Revises: 2fd85ae4f7b5
Create Date: 2026-03-13 19:26:55.477938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d7b0d4e5f63'
down_revision = '2fd85ae4f7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=32), server_default='active', nullable=True))
        batch_op.add_column(sa.Column('status_changed_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_users_email', ['email'])
        batch_op.drop_column('displayname')
        batch_op.drop_column('picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('displayname', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint('uq_users_email', type_='unique')
        batch_op.drop_column('status_changed_at')
        batch_op.drop_column('status')
        batch_op.drop_column('created_at')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
