"""Added read Column on messages

Revision ID: 2fd85ae4f7b5
Revises: e238c08e5a85
Create Date: 2026-03-06 19:30:11.175800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd85ae4f7b5'
down_revision = 'e238c08e5a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.Boolean(), server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('read')

    # ### end Alembic commands ###
