"""added follows table

Revision ID: 74a49eb7bd53
Revises: d7f02782496e
Create Date: 2026-03-30 11:09:34.800178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a49eb7bd53'
down_revision = 'd7f02782496e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followed_id', name='unique_follow')
    )
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index('idx_follower_followed', ['follower_id', 'followed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follows_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_follows_followed_id'), ['followed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follows_follower_id'), ['follower_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follows_follower_id'))
        batch_op.drop_index(batch_op.f('ix_follows_followed_id'))
        batch_op.drop_index(batch_op.f('ix_follows_created_at'))
        batch_op.drop_index('idx_follower_followed')

    op.drop_table('follows')
    # ### end Alembic commands ###
