"""added link field in user_profile table

Revision ID: 9a0f0ac968c9
Revises: 2d7b0d4e5f63
Create Date: 2026-03-16 11:41:54.208282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a0f0ac968c9'
down_revision = '2d7b0d4e5f63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###
